#!/bin/bash
set -e

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

echo "Config update started"

INSTALL_DIR=$(pwd)

rm -rf /etc/osmocom

cp -r "$INSTALL_DIR"/configs/osmocom /etc/osmocom
cp -r "$INSTALL_DIR"/configs/asterisk/* /etc/asterisk/

chown asterisk:asterisk /etc/asterisk
chown asterisk:asterisk /etc/asterisk/*

echo "Config update ended"
