#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

echo "Services update started"

INSTALL_DIR=`pwd`

cp -r $INSTALL_DIR/services/* /lib/systemd/system/
systemctl daemon-reload

echo "Services update ended"








