#!/bin/bash
set -e

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

echo "System configs update started"

INSTALL_DIR=$(pwd)

cp "$INSTALL_DIR"/configs/journalctl/journald.conf /etc/systemd/journald.conf
systemctl restart systemd-journald

cp -v "$INSTALL_DIR"/configs/sysctl/sysctl.conf /etc/sysctl.conf
# reload system settings(read /etc/sysctl.conf)
sysctl --system

cp -v "$INSTALL_DIR"/configs/systemd/system.conf /etc/systemd/system.conf
systemctl daemon-reload

echo "System configs update ended"
