#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

echo "Config update started"

INSTALL_DIR=`pwd`

rm -rf /etc/osmocom
rm -rf /etc/asterisk
rm -rf /etc/kamailio

cp -r $INSTALL_DIR/configs/osmocom /etc/osmocom
cp -r $INSTALL_DIR/configs/asterisk /etc/asterisk
cp -r $INSTALL_DIR/configs/kamailio /etc/kamailio

chown asterisk:asterisk /etc/asterisk
chown asterisk:asterisk /etc/asterisk/*

echo "Config update ended"








